common:
  worlds_dir: "data/input/worlds"
  output_dir: "data/output"
  logs_dir: "data/logs"
  models_dir: "data/models"
  world_name: "LEEFNUT 1.18 MAP FINAL"
  lim_tag: "plain"
  xlim: [-220, -136]
  ylim: [65, 89]
  zlim: [225, 304]
  

block2vec:
  embed_dim: 5
  epochs: 200

singan:
  num_scales: 9
  scales: [0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00]
  learning_rate: 5e-4
  n_iters: 2501
  noise_w: 0.1

export:
  empty_world_dir: "data/input/worlds/Empty World"